spring.application.name=user-shop-service
server.port=8080
server.address=0.0.0.0

# Te trzy wartości i tak będą nadpisane przez env w docker-compose,
# ale zostawmy je sensownie:
spring.datasource.url=jdbc:mysql://localhost:3306/terraSystem
spring.datasource.username=root
spring.datasource.password=devpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
